name: Build and Test

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request: {}

jobs:
  build_and_test_ubuntu:
    name: Build and Test on Ubuntu
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y -V install \
            cmake \
            libicu-dev
      - name: Run CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
      - name: Build
        working-directory: build
        run: |
          make -j$(nproc)
      - name: Test
        working-directory: build
        run: |
          ctest --output-on-failure
  build_and_test_macos:
    name: Build and Test on macOS
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          brew update
          brew install \
            cmake \
            icu4c
      - name: Run CMake
        run: |
          mkdir build
          cd build
          PKG_CONFIG_PATH="$(brew --prefix icu4c)/lib/pkgconfig" cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
      - name: Build
        working-directory: build
        run: |
          make -j$(sysctl -n hw.logicalcpu)
      - name: Test
        working-directory: build
        run: |
          ctest --output-on-failure
