name: Build and Test

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request: {}

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y -V install \
            cmake \
            libicu-dev
      - name: Run CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=Yes ..
      - name: Build
        working-directory: build
        run: |
          make -j$(nproc)
      - name: Test
        working-directory: build
        run: |
          make test
